server:
  port: 8092

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:shop}
      username: ${DB_USER:root}
      password: ${DB_PWD:root}

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

jwt:
  token:
    header: Authorization
    head: 'Bearer '
    secret: mall-member-secret
    period: 7200  #秒

file:
  active-disk: local
  disks:
    local:
      location: J:\upload
      host: http://pic.chdt.local/upload

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

snowflake:
  start-timestamp: 1633340685839
  data-center-bits: 3
  machine-bits: 4
  sequence-bits: 10

# RSA 加密密钥
rsa:
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArPCt5JguBsVO8xOSW3jjQIk7qFyjbSxdLaeb4M8P46on5dSXZPph+wfKmNK1rzPNSNzCIzM5H+wDCrxJ8QAfnNTzoQ+NxLkoVtVy/eKF1qFOGdZQn4m68hDbVsrzwaPrX/LDs+VsX39sKOLvogLw738LNgrJCQMUbQcSiPb3N675UVMaDjixzzLZGvAWVsFBp+fyQRs+GeozgPdzx4dT2AsdMghCzV/6DQYqIQ78bKs4ZaVD6D3j4JKEn6byeSYXBmVw7UwWHN7v+AzVTPO79o8ohGtxlv70awZri4qkPEoyMKvtoesy+mG9toc0+GgrM0zRBaLnV3coYOV2ZNia4QIDAQAB
  private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCs8K3kmC4GxU7zE5JbeONAiTuoXKNtLF0tp5vgzw/jqifl1Jdk+mH7B8qY0rWvM81I3MIjMzkf7AMKvEnxAB+c1POhD43EuShW1XL94oXWoU4Z1lCfibryENtWyvPBo+tf8sOz5Wxff2wo4u+iAvDvfws2CskJAxRtBxKI9vc3rvlRUxoOOLHPMtka8BZWwUGn5/JBGz4Z6jOA93PHh1PYCx0yCELNX/oNBiohDvxsqzhlpUPoPePgkoSfpvJ5JhcGZXDtTBYc3u/4DNVM87v2jyiEa3GW/vRrBmuLiqQ8SjIwq+2h6zL6Yb22hzT4aCszTNEFoudXdyhg5XZk2JrhAgMBAAECggEAR0pP5NP25UOg8AM5agvDYm8v8I9/rxmCr7dQQrQY0LjsCYpBfpbYnSrxEV6LFtY74bVfMjODcO1Rs7M6p+ZtIbGHXPWUc2wAfQswhAhFM9z63RvD0IBuWCsqv/SZ11FDTiI9GoOQ0S0t4Qzry9V6jL/KV1TK2rQyT1+C/IMSFhmSktkSnq1WoJ12Yfn1wlj8psEDYXN8Z7lzMTX4RKqXSw7NgG/bEMg7VVhmqpRyKvsolSEk+T+WtN7oWS9L+pUaPcfy/gdyVl2CJ7Xc2+gaMov9D/+Cb0kgz7oiszsvaDpWizqHo2SoPaioUUb28x86oRG16sREtZh/jNcJl8iCoQKBgQD92nh2NAwp36BzlfU9oCdrLWqQu0JyuF/JNE3Zx9cWLnfkOD1L5jX9gCSRiDnGk99CrUVSBLLmYRHOvs9LqHa54UCmYYSG7mKXwLJV8FC7/JF1S3KsG9X8sgzNRp/iNKlECJlIzqWPu7kEEUa7JmIo1XSEpXCEMXu+maiwG4sbgwKBgQCuZw06LgRNlXl3MBKnBNh2vJ2UI3XPmIViY+yZ0nr8pHAxyANBfa9xixovk38zRlzx2fDeKAd3M6SEhvBQ1RJSbdJhuWRmfnandfhIw5x/nDwrL+hMWmCvUZ9PJtd6XCMG0Ryy8e7hTwZdrGJvakLT5ORJEtphYxvity4BzlLuywKBgCdJy8EHlyZX7P5WpCkQg2lMEyUpRkR5EqISTUY6bqiJMpcIuTvo+kwsq/w2KDL6qeAo7wSdo46SUW49C9o6zX1BRn85sogrlujDsxYn5mbh1SVhMvM+L6U3bVHL72zUF6pm5kplaSxQsnbVsau/agvF1Y2+CSb8fZlnMLto1+O/AoGASzxJiH+xe4awD6q9YS/F8fMMR4vElvnFENzqhLE4PSTzAYa3YNlHhkPr1/pZNVV1YyARuMSr89BjeIh9w2EntkeKKn4/wbdsmHFb2ogIS0Sq8DaKj+WtL/SWNR8cdbypn5c2OjwEQU5GAMMM8+NzUNW9ZYisjLakoPlE76KCRGECgYEA1QQK0Ikh/aWDUIlN+PLLegRRsJDtzJYwQV2S49UB5PoaNcpRHjriy5T6OA6sqyNYiPHgxOrcx+4GHqp8cX5htNW1zQelea/JJHDjoYK8dwIOs9CPL5LU7KvY+xq/tjwnbNtld+iDNidz4nc6FBC5GXEmDVXG1vZFBWTkhYxb7oY=
